[project]
name = "julia-forge"
version = "0.1.0"
description = "Automation to build a julia package(s) for julia-forge"
authors = ["Wolf Vollprecht <w.vollprecht@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]

[tasks]

[dependencies]
rattler-build = ">=0.15,<1"
