name: Build all packages

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:

  build:
    strategy:
      matrix:
        include:
          - { target: linux-64,  os: ubuntu-20.04 }
          - { target: win-64,    os: windows-latest }
          # force older macos-13 to get x86_64 runners
          - { target: osx-64,    os: macos-13 }
          - { target: osx-arm64, os: macos-14 }
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: prefix-dev/setup-pixi@v0.5.1
      with:
        pixi-version: v0.24.2
        cache: true

    - name: Add .pixi/envs/default to the $PATH
      shell: bash
      run: |
        echo "$(pwd)/.pixi/envs/default/bin" >> $GITHUB_PATH

    - name: Run code in changed subdirectories
      shell: bash
      env:
        TARGET_PLATFORM: ${{ matrix.target }}

      run: |
        rattler-build build --recipe-dir . \
          --skip-existing=all --target-platform=$TARGET_PLATFORM \
          -c conda-forge -c https://prefix.dev/julia-forge

    - name: Upload all packages
      shell: bash
      # do not upload on PR
      if: github.event_name == 'push'
      env:
        PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}
      run: |
        # ignore errors because we want to ignore duplicate packages
        for file in output/**/*.conda; do
          rattler-build upload prefix -c julia-forge "$file" || true
        done
